services:
  app:
    build:
      context: .
      args:
        VITE_RECAPTCHA_SITE_KEY: ${VITE_RECAPTCHA_SITE_KEY}
        VITE_SITE_URL: ${VITE_SITE_URL:-https://rotki.com}
    ports:
      - '4000:4000'
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_APP_ID=${DISCORD_APP_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      - DISCORD_ROLE_ID=${DISCORD_ROLE_ID}
      - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
      - REDIS_HOST=redis
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - invite-data:/data
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: redis:7.2-alpine
    restart: on-failure

volumes:
  invite-data:
