version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
